### ISSUE TITLE
Different results when report loaded in Jenkins job

### ISSUE THREAD

**Issue by hallabassee** [alienfast/cucumber_statistics#13]
When I run a test feature using a Jenkins job, the report is missing 3 out of 5 scenarios on the Scenarios tab and zero steps are showing on the Steps tab even though it says there were 8 steps completed (it should say there were 120 steps completed). 

Using:
- Ruby 2.3.1
- Cucumber 2.4.0
- require 'cucumber_statistics/autoload' in my env.rb
- Jenkins ver. 2.51

**Comment by rosskevin** [comment]
@hallabassee I don't use Jenkins, and I don't have any time to give this plugin so you'll have to debug this yourself.  I certainly welcome any PRs.  It's actually not too complicated so you'll probably be able to figure it out quickly.  My guess is that your issue isn't Jenkins related, but some combination of gem versions and you should be able to reproduce this with or without Jenkins.  Regardless, we don't have any conditionals about such an environment.
