### ISSUE TITLE
uninitialized constant CucumberStatistics::Formatter::OverallStatistics

### ISSUE THREAD

**Issue by bricelalu** [alienfast/cucumber_statistics#4]
When I try both:
- with autoload or,
- with --format CucumberStatistics::Formatter

I have the issue below: (I have tested with both ruby 2.1.4[installed with rvm] and ruby 2.0.0[native, without rvm] and ruby 1.9.3[with rvm])

I dont have a rails application, maybe this is the root cause ?

Error creating formatter: CucumberStatistics::Formatter (NameError)
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber_statistics-1.0.3/lib/cucumber_statistics/formatter.rb:8:in `initialize'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/configuration.rb:183:in `new'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/configuration.rb:183:in `block in formatters'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/configuration.rb:178:in `map'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/configuration.rb:178:in `formatters'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/configuration.rb:76:in `build_tree_walker'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/runtime.rb:46:in `run!'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/lib/cucumber/cli/main.rb:47:in `execute!'
/home/user/.rvm/gems/ruby-1.9.3-p550/gems/cucumber-1.3.17/bin/cucumber:13:in `<top (required)>'
/home/user/.rvm/gems/ruby-1.9.3-p550/bin/cucumber:23:in `load'
/home/user/.rvm/gems/ruby-1.9.3-p550/bin/cucumber:23:in `<main>'
/home/user/.rvm/gems/ruby-1.9.3-p550/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-1.9.3-p550/bin/ruby_executable_hooks:15:in `<main>'

**Comment by allewun** [comment]
I'm also encountering this, both with autoload and `--format CucumberStatistics::Formatter`. Similar stack trace:
```
> cucumber --format CucumberStatistics::Formatter                                                                                                                                                                  Mon 19-Jan-2015 02:36 PM
uninitialized constant CucumberStatistics::Formatter::OverallStatistics
Error creating formatter: CucumberStatistics::Formatter (NameError)
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber_statistics-1.0.3/lib/cucumber_statistics/formatter.rb:8:in `initialize'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/configuration.rb:183:in `new'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/configuration.rb:183:in `block in formatters'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/configuration.rb:178:in `map'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/configuration.rb:178:in `formatters'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/configuration.rb:76:in `build_tree_walker'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/runtime.rb:46:in `run!'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/lib/cucumber/cli/main.rb:47:in `execute!'
/Users/allen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cucumber-1.3.18/bin/cucumber:13:in `<top (required)>'
/Users/allen/.rbenv/versions/2.1.5/bin/cucumber:23:in `load'
/Users/allen/.rbenv/versions/2.1.5/bin/cucumber:23:in `<main>'
```

Using rbenv with ruby 2.1.5 and cucumber 1.3.18 on a non-rails project.

**Comment by rosskevin** [comment]
@allewun I have been unable to recreate, so if you can do so and provide a sample, or fix and provide a pull request I am open to helping.

**Comment by bricelalu** [comment]
@rosskevin Your doc is not complete:

I've fixed the issue by adding the following lines in my env.rb:
require 'cucumber_statistics'
require 'cucumber_statistics/autoload'

In your documentation, you mention only this line:
require 'cucumber_statistics/autoload'

**Comment by rosskevin** [comment]
@bricelalu - interesting, I don't need that in the rails env but it does make sense.  I've addressed it by requiring `cucumber_statistics` from the `autoload` file and pushed v1.0.4.  Please reopen if it does not resolve it.
