### ISSUE TITLE
Error with cucumber 2.3.2

### ISSUE THREAD

**Issue by gustavoriveray** [alienfast/cucumber_statistics#6]
Getting the following error

`uninitialized constant CucumberStatistics::Formatter::OverallStatistics (NameError)
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber_statistics-2.1.1/lib/cucumber_statistics/formatter.rb:8:in `initialize'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:203:in `new'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:203:in `create_formatter'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:192:in `block in formatters'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/configuration.rb:176:in `block in formatter_factories'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/configuration.rb:171:in `map'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/configuration.rb:171:in `formatter_factories'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:191:in `formatters'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:173:in `report'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:65:in `run!'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/user/.rvm/gems/ruby-2.3.0/gems/cucumber-2.3.2/bin/cucumber:8:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in `load'
/Users/user/.rvm/gems/ruby-2.3.0/bin/cucumber:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'`

Environment:

rvm 1.26.11
ruby 2.3.0
Cucumber 2.3.2
cucumber_statistics 2.1.1

I was able to solve it by adding 

require 'cucumber_statistics/step_statistics'
require 'cucumber_statistics/overall_statistics'
require 'cucumber_statistics/unused_steps'
require 'cucumber_statistics/renderer'
require 'cucumber_statistics/configuration'

to formatter.rb

Also when there's scenario outlines it doesn't work it brings a blank table, unless you use --expand option

**Comment by gustavoriveray** [comment]
Also, when you add --out then_my_own_file_name.html doesn't respect that and it puts it on the same file always

**Comment by rosskevin** [comment]
This seems relevant to the issue: 

https://github.com/alienfast/cucumber_statistics/issues/4#issuecomment-70624420

The second Item is another issue entirely. Feel free to fix it and send a PR.

**Comment by rosskevin** [comment]
On the first item, all seems well, so it must be environmental.

On the second item, output files are hardcoded, there are now multiple files.  If you want to take on a PR for this then please do so.
