### ISSUE TITLE
StepStatistics.record 's file_colon_line parameter 

### ISSUE THREAD

**Issue by callahat** [alienfast/cucumber_statistics#7]
Is this parameter doing something ultimately useful? I traced through the code and it looks like the last file that has a particular step in it wins. I see this end up as a cell title, but that seems to be it. This seems to be confirmed by the step_statistics.html.haml and  the resultant step_statistics.html output file. The same step could appear across multiple files, but the title will always just be one file.

Mainly asking because I'm working on adding timings for scenarios and might have missed something.

**Comment by rosskevin** [comment]
If I recall correctly, it is only the last one as you mentioned.  It's only useful to get a reference to track down the step.  I haven't revisited this for a while, we still use it but we've mostly optimized what we could find.
