### ISSUE TITLE
Missing Timings/Step Entries

### ISSUE THREAD

**Issue by callahat** [alienfast/cucumber_statistics#8]
There seem to be issues with backgrounds and scenario outlines.

Background steps seem to appear once (even if they would run more than once in a file - possibly skewing results)

Scenario outline steps do not seem to be picked up at all by the formatter.

Running cucumber 2.3.3

I setup a repo where this can be observed here: https://github.com/callahat/cuke_demo
in the `cucumber_statistics` branch. (https://github.com/callahat/cuke_demo/tree/cucumber_statistics)
There is an example output file from the formatter that was generated with:
```
bundle exec cucumber features  --format CucumberStatistics::Formatter
```

From the counts for the calculator steps, there should be twice as many from the scenario outlines.

**Comment by rosskevin** [comment]
Feel free to PR,  I'm unlikely to have time ti debug and fix an issue for you.

**Comment by callahat** [comment]
My time's pretty short at the moment as well, but I did come across a workaround for the scenario outline missing steps. By using `--expand` as an additional option the outline steps show up. The background steps still only get counted once.

**Comment by rosskevin** [comment]
Was this fixed in your PR @callahat? or could this relate to #9?

**Comment by callahat** [comment]
I didn't address this in the PR, and I think #9 is unrelated. When looking into it a while ago it seemed to be a feature of how Cucumber reports the steps. `--expand` made the expected timings show up, but I didn't look into whether or not there's a way within the formatter to 'force' Cucumber to report everything to the formatters.

**Comment by callahat** [comment]
Turns out there is a new formatter api that should be used instead. 

( Cuke group thread on google groups: https://groups.google.com/forum/#!topic/cukes/HIGakoahWEA )

I'm ok with closing this issue as the solution involves updating to use the new api.

**Comment by rosskevin** [comment]
thanks for looking in on that, I've added #11
